name       : dnscrypt-proxy-gui
version    : 1.21.16
release    : 4
source     :
    - https://github.com/F1ash/dnscrypt-proxy-gui/archive/1.21.16.tar.gz : 2cbfc2dcd5a378669fbc25cc26535e686046385a9a139d71b23269207030997b
license    : GPL-2.0-or-later
component  : network.util
summary    : Qt/KF5 GUI wrapper over dnscrypt-proxy
description: |
    Contains systemd instantiated unit for control proxying service. Works
    with local address and service list from dnscrypt-proxy package.
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(Qt5Core)
    - extra-cmake-modules
    - kauth-devel
    - knotifications-devel
rundeps    :
    - dnscrypt-proxy
setup      : |
    %cmake -DSHARE_INSTALL_PREFIX=/usr/share
build      : |
    %make
install    : |
    %make_install
