name       : dnscrypt-proxy-gui
version    : 1.11.15
release    : 3
source     :
    - https://github.com/F1ash/dnscrypt-proxy-gui/archive/1.11.15.tar.gz : 1a3a32f252cd6146d40c9835d6878a4279427de23dbcc89f69ce89aaab52bbdf
license    : GPL-2.0
component  : network.util
summary    : Qt/KF5 GUI wrapper over dnscrypt-proxy
description: |
    Contains systemd instantiated unit for control proxying service. Works
    with local address and service list from dnscrypt-proxy package.
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(Qt5Core)
    - extra-cmake-modules
    - kauth-devel
    - knotifications-devel
rundeps    :
    - dnscrypt-proxy
setup      : |
    %cmake -DSHARE_INSTALL_PREFIX=/usr/share
build      : |
    %make
install    : |
    %make_install
